### PR TITLE
archlinux: Permit using xorg-server 1.18.x

### PR DESCRIPTION
**Pull request by pqg**
As Arch adopted xorg-server v1.18.0 two weeks ago, this was preventing gui-agent-linux from building.

Basic testing suggests that everything works fine, but I've not trialled it extensively yet.  It may be wise to defer the pull until Olivier can be asked about the reason behind the limit.

### CODE REVIEW

**Comment by marmarek** [comment]
How does Archlinux handle rebuilding X drivers? When you update X server (major upgrade), all the drivers need to be rebuild with matching headers. Is it handled automatically?

**Comment by pqg** [comment]
I'm afraid I'm not familiar with Arch's build process.  Browsing an Arch repository archive ( http://ala.seblu.net/packages/x/ ) suggests that the driver binaries were also all updated around the 11th.

Or maybe I am misunderstanding the thrust of your question?

**Comment by marmarek** [comment]
Does Archlinux binary packages have some automatic dependencie (besides
those set directly in PKGBUILD)? I mean - if I have a X driver package
built using version 1.17.x, would it be recorded somewhere in the
package? Otherwise if I update xorg-server, but not the driver (which
will be possible without such automatic dependency), the driver will not
load.

In Qubes it means GUI-less system...

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by pqg** [comment]
Ah, well I lack a deep understanding of the Archlinux package format, however [xorg-server 1.18.0-3](https://www.archlinux.org/packages/extra/x86_64/xorg-server/) sets the following:

~~~
Provides: X-ABI-EXTENSION_VERSION=9.0, X-ABI-VIDEODRV_VERSION=20, X-ABI-XINPUT_VERSION=22.1, x-server
~~~

Then, e.g., [xf86-video-fbdev 0.4.4-5](https://www.archlinux.org/packages/extra/x86_64/xf86-video-fbdev/) sets:

~~~
Dependencies: X-ABI-VIDEODRV_VERSION=20
Conflicts: X-ABI-VIDEODRV_VERSION<20, X-ABI-VIDEODRV_VERSION>=21, xorg-server<1.16
~~~

It looks like the maintainers are tracking compatibility this way.

**Comment by marmarek** [comment]
Is it handled automatically? Or some code for that need to be added to
PKGBUILD? In other words - can you check if qubes-gui-agent package has
similar dependencies?

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by pqg** [comment]
Right.  It's not automatic; it indeed requires maintainers to manually adjust when rebuilding for the latest Xorg.  I've adjusted this PR to include the same Requires and Conflicts as the video and input drivers in the official Arch repos.  The resulting package installs successfully in my Arch template.

For reference, the error message generated when building with outdated ABI Conflicts is as follows:

~~~
==> Making package: qubes-vm-gui 3.1.1-3 
==> Checking runtime dependencies...
==> Installing missing dependencies...
error: target not found: X-ABI-VIDEODRV_VERSION=19
==> ERROR: 'pacman' failed to install missing dependencies.
/home/user/src/qubes-builder/qubes-src/builder-archlinux/Makefile.archlinux:120: recipe for target 'dist-package' failed
~~~

**Comment by marmarek** [comment]
I'm not sure what is happening here... I see dependencies on both xorg-server package version and X-ABI_*_VERSION virtual provides. Is it really necessary? I think one of them is enough.

**Comment by marmarek** [comment]
I've merged #15 , is it still needed?

**Pull request closed without merging**
