### PR TITLE
xsession: rename scripts to match Xsession requirements (#1172)

### PR DESCRIPTION
**Pull request by marmarek**
Xsession on Debian uses `run-parts --list`. It strictly requires that
files are named with letters, numbers and dash only. Especially no dots
are allowed. Because of that, remove '.sh' suffix, same as other files
there.

Fixes QubesOS/qubes-issues#1172

### CODE REVIEW

**Comment by adrelanos** [comment]
The makefile still contains `.sh`.

**Comment by marmarek** [comment]
In Fedora part - yes, I haven't renamed the files there. In debian part
is copies all the files:
```
    install -d $(DESTDIR)/etc/X11/Xsession.d
    install appvm-scripts/etc/X11/Xsession.d/* $(DESTDIR)/etc/X11/Xsession.d/
```

Am I missing some other place?

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by adrelanos** [comment]
Ah. Ok.

No.

If you don't think renaming those also so those match would simplify the implementation, then this can stay as is.

**Comment by marmarek** [comment]
On Fedora all the scripts there have '.sh' suffix, so it would be more
consistent.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by adrelanos** [comment]
I have merged your branch into https://github.com/adrelanos/qubes-gui-agent-linux since those are essential for Whonix. Test result: works for me.

**Comment by marmarek** [comment]
Thanks. This will probably go as an update after R3.0 release.

**Pull request merged**
