### PR TITLE
Archfix 201507

### PR DESCRIPTION
**Pull request by ptitdoc**

### CODE REVIEW

**Comment by ptitdoc** [comment]
Recreated commits from scratch because of a git reset error (lost all local changes). The package build successfully, but I have to retest the packet the full template.

**Comment by marmarek** [comment]
I'll merge those, but one question: is it possible to specify pulseaudio+xorg dependencies based on versions used during build? This way it wont be necessary to update PKGBUILD at each pulseaudio upgrade.

**Comment by ptitdoc** [comment]
It will be hard because I don't wan't to force user to update agents after each minor releases.

Currently, the PKGBUILD will be updated only on major releases of Xorg and Pulseaudio, which are anyway quite rare and are the only cases I detected where sound or AppVM booting will be broken.

**Comment by marmarek** [comment]
Yes, I'm talking about major versions only. In Fedora, pulseaudio package is versioned 3.0, 4.0, 5.0 and so on (minor updates are hidden in package release number, like 5.0-25). Then the package has dependency dynamically generated:

    %define pa_ver %((pkg-config --modversion libpulse 2>/dev/null || echo 0.0) | cut -d "-" -f 1)
    Requires:   pulseaudio = %{pa_ver}

We don't have anything similar for X server, but this is because Fedora (nor Debian) doesn't change X server major version withing one distribution version. This of course isn't true for rolling distribution.

**Pull request merged**
